CREATE DATABASE [PRODUCT DATABASE V1]

USE [PRODUCT DATABASE V1]


-- TABLE 1:  CUSTOMERS_DATA TABLE
CREATE TABLE CUSTOMERS_DATA
(
CustomerKey INT PRIMARY KEY,
FirstName	VARCHAR(30) NOT NULL,
MiddleName	VARCHAR(30) NOT NULL,
LastName	VARCHAR(30) NOT NULL,	
Gender		CHAR NOT NULL CHECK (GENDER IN ('M','F')),
MStatus		CHAR NOT NULL CHECK (MStatus IN ('M','S')),
Income		FLOAT	NOT NULL CHECK (Income >= 10000)
)






-- TABLE 2:	 PRODUCTS_DATA TABLE
CREATE TABLE PRODUCTS_DATA
(
ProductKey INT PRIMARY KEY,
ProductName	VARCHAR(30) NOT NULL,
Class		CHAR NOT NULL CHECK (Class IN ('L','M','H')),
Color		VARCHAR(20) NOT NULL CHECK (Color IN ('White','Black', 'Red', 'Green','Other')),
UnitPrice	FLOAT	NOT NULL CHECK (UnitPrice >= 1)
)

-- TABLE 3:  TIME_DATA TABLE
CREATE TABLE TIME_DATA
(
TimeKey		INT PRIMARY KEY,
YEAR		INT,
QUARTER		INT,
MONTH		VARCHAR(30),
WEEK		INT,
DAY			DATE DEFAULT GETDATE()
)

-- TABLE 4:	 SALES_DATA
CREATE TABLE SALES_DATA
(
SALE_ID			INT		IDENTITY(10001,1),
CustomerKey		INT		REFERENCES CUSTOMERS_DATA(CustomerKey),
ProductKey		INT		REFERENCES PRODUCTS_DATA(ProductKey),
TimeKey			INT		REFERENCES TIME_DATA(TimeKey),
SalesAmount		FLOAT	CHECK (SalesAmount >= 1) NOT NULL,
TaxAmt			FLOAT	CHECK (TaxAmt >= 0.5) NOT NULL
)


-- NOW, LETS INSERT SOME TEST DATA
INSERT INTO CUSTOMERS_DATA VALUES (1001, 'JOHN', 'M','GEORGE', 'M','M', 250000)
INSERT INTO CUSTOMERS_DATA VALUES (1002, 'AMIN', 'A','SHAIK', 'M','S', 150000)
INSERT INTO CUSTOMERS_DATA VALUES (1003, 'SAI', ' ','JACK', 'M','S', 200000)

INSERT INTO PRODUCTS_DATA VALUES (101, 'CAPS', 'M', 'RED', 2),(102, 'CAPS', 'H', 'RED', 2)
INSERT INTO PRODUCTS_DATA VALUES (103, 'GLOVES', 'M', 'GREEN', 2),(104, 'GLOVES', 'H', 'GREEN', 2)

INSERT INTO TIME_DATA VALUES (1, 2020, 1, 'JANUARY', 4, '2020-01-30'), (2, 2020, 1, 'JANUARY', 4,'2020-01-31')

INSERT INTO SALES_DATA VALUES (1001, 101, 1, 300, 30)
INSERT INTO SALES_DATA VALUES (1001, 104, 2, 900, 80)