-- TASK 1: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MAXIMUM SALARY?
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL=(SELECT MAX(EMP_SAL) FROM EMPLOYEE_INFO)

-- TASK 2: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM SALARY?
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL=(SELECT MIN(EMP_SAL) FROM EMPLOYEE_INFO)

-- TASK 3: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM OR MAXIMUM SALARY?
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL=(SELECT MAX(EMP_SAL) FROM EMPLOYEE_INFO)
UNION
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL=(SELECT MIN(EMP_SAL) FROM EMPLOYEE_INFO)

-- TASK 4: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM OR MAXIMUM SALARY IN A SPECIFIC ORDER?
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL=(SELECT MAX(EMP_SAL) FROM EMPLOYEE_INFO)
UNION ALL
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL=(SELECT MIN(EMP_SAL) FROM EMPLOYEE_INFO)

-- TASK 5: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM SALARY FROM INDIA?
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL =  (   SELECT MIN(EMP_SAL) FROM EMPLOYEE_INFO WHERE EMP_CNTRY= 'INDIA'  )
WHERE EMP_CNTRY= 'INDIA'

-- TASK 6: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MAXIMUM SALARY FROM INDIA?
SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL=(SELECT MAX(EMP_SAL) FROM EMPLOYEE_INFO WHERE EMP_CNTRY='INDIA')


-- TASK 7: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MAXIMUM SALARY FROM INDIA WITH NAME STARTING WITH LETTER A ?
SELECT * FROM EMPLOYEE_INFO 
WHERE 
EMP_SAL IN (SELECT MAX(EMP_SAL) FROM EMPLOYEE_INFO) AND  EMP_CNTRY = 'INDIA' AND EMP_FNAME LIKE 'A%' 


-- TASK 8: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM SALARY FROM INDIA WITH NAME ENDING WITH LETTER N ?

SELECT * FROM EMPLOYEE_INFO 
WHERE 
EMP_SAL IN (SELECT MIN(EMP_SAL) FROM EMPLOYEE_INFO) AND  
EMP_CNTRY = 'INDIA' AND EMP_FNAME LIKE '%N' 

-- TASK 9: HOW TO REPORT LIST OF ALL EMPLOYEES WITH HIGHEST SALARY ?

SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL IN (SELECT MAX(EMP_SAL) FROM EMPLOYEE_INFO)

-- TASK 10: HOW TO REPORT LIST OF ALL EMPLOYEES WITH SALARY VALUE ABOVE THE MINIMUM SALARY ?

SELECT * FROM EMPLOYEE_INFO WHERE EMP_SAL > (SELECT MIN(EMP_SAL) FROM EMPLOYEE_INFO)
