TASK 1: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MAXIMUM SALARY?

TASK 2: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM SALARY?

TASK 3: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM OR MAXIMUM SALARY?

TASK 4: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM OR MAXIMUM SALARY IN THE ORDER OF THEIR EMPLOYEE IDs?

TASK 5: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM SALARY FROM INDIA?

TASK 6: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MAXIMUM SALARY FROM INDIA?

TASK 7: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MAXIMUM SALARY FROM INDIA WITH NAME STARTING WITH LETTER A ?

TASK 8: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MINIMUM SALARY FROM INDIA WITH NAME ENDING WITH LETTER N ?

TASK 9: HOW TO REPORT LIST OF ALL EMPLOYEES WITH HIGHEST SALARY ?

TASK 10: HOW TO REPORT LIST OF ALL EMPLOYEES WITH SALARY VALUE ABOVE THE MINIMUM SALARY ?

