-- QUERY TO REPORT LIST OF ALL STUDENTS FROM ALL COURSES 
SELECT * FROM TBLCOURSES
INNER JOIN
TBLSTUDENTS 
ON
TBLSTUDENTS.STD_COURSE_ID = TBLCOURSES.COURSE_ID

-- QUERY TO REPORT LIST OF ALL STUDENTS FROM ROBOTICS COURSE?
SELECT * FROM TBLCOURSES
INNER JOIN
TBLSTUDENTS 
ON
TBLSTUDENTS.STD_COURSE_ID = TBLCOURSES.COURSE_ID
WHERE TBLCOURSES.COURSE_NAME = 'ROBOTICS'



-- QUERY TO REPORT LIST OF ALL STUDENTS FROM A GIVEN COURSE?
CREATE FUNCTION fnReportStudents (@CourseName varchar(30))
RETURNS table
AS
RETURN (
SELECT * FROM TBLCOURSES
INNER JOIN
TBLSTUDENTS 
ON
TBLSTUDENTS.STD_COURSE_ID = TBLCOURSES.COURSE_ID
WHERE TBLCOURSES.COURSE_NAME = @CourseName    	)


SELECT * FROM fnReportStudents ('ROBOTICS')		-- PARSE & COMPILE, OPTIMIZE, EXECUTE
SELECT * FROM fnReportStudents ('COMPUTERS')	-- PARSE & COMPILE, OPTIMIZE, EXECUTE



-- QUERY TO REPORT LIST OF ALL STUDENTS FROM A GIVEN COURSE?
CREATE PROCEDURE uspReportStudents (@CourseName varchar(30))
AS
SELECT * FROM TBLCOURSES
INNER JOIN
TBLSTUDENTS 
ON
TBLSTUDENTS.STD_COURSE_ID = TBLCOURSES.COURSE_ID
WHERE TBLCOURSES.COURSE_NAME = @CourseName    	

	
EXEC uspReportStudents 'ROBOTICS'	-- PARSE & COMPILE, OPTIMIZE, EXECUTE
EXEC uspReportStudents 'COMPUTERS'	-- DIRECT EXECUTING,REUSING OPTIMIZED EXECUTION PLAN