USE TEMPDB 
GO

CREATE TABLE tblPopulation
(
Country VARCHAR(100),
[State] VARCHAR(100),
City VARCHAR(100),
Population INT
)

INSERT tblPopulation VALUES			('COUNTRY1', 'STATE1','CITY1',9 ),
	('COUNTRY1', 'STATE1','CITY2',8 ), 	('COUNTRY1', 'STATE2','CITY1',5.5), 
	('COUNTRY1', 'STATE2','CITY2',7.5), 	('COUNTRY2', 'STATE1','CITY1',9.5), 
	('COUNTRY2', 'STATE1','CITY2',2.5),	('COUNTRY2', 'STATE2','CITY1',1.5),	
	('COUNTRY3', 'STATE1','CITY1',30),		('COUNTRY3', 'STATE1','CITY2',20)

	INSERT tblPopulation VALUES			(NULL, 'STATE1','CITY1',9 )

-- QUERY 1: HOW TO REPORT LIST OF ALL POPULATION DETAILS?
SELECT * FROM tblPopulation

-- QUERY 2: HOW TO REPORT LIST OF ALL COUNTRY NAMES?
SELECT Country FROM tblPopulation

-- QUERY 3: HOW TO REPORT LIST OF ALL UNIQUE COUNTRIES DETAILS?
SELECT Country FROM tblPopulation 
GROUP BY Country

-- QUERY 4: HOW TO REPORT TOTAL POPULATION DETAILS?
SELECT sum(Population) AS TOTAL_POP FROM tblPopulation

-- QUERY 5: HOW TO REPORT COUNTRY WISE TOTAL POPULATION DETAILS?
SELECT COUNTRY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY COUNTRY 

-- RULE :  WHENEVER WE USE GROUP BY THEN COLUMNS USED IN SELECT SHOULD ALSO BE IN GROUP BY
SELECT COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY COUNTRY 

-- RULE : WHENEVER WE USE GROUP BY THEN COLUMNS USED IN SELECT SHOULD ALSO BE INCLUDED IN GROUP BY

-- QUERY 6: HOW TO REPORT COUNTRY WISE, STATE WISE  TOTAL POPULATION?
SELECT COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY COUNTRY, STATE
 
-- QUERY 7: HOW TO REPORT COUNTRY WISE, STATE WISE, CITY WISE TOTALS?
SELECT COUNTRY, STATE, CITY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY COUNTRY, STATE, CITY

-- QUERY 8: HOW TO APPLY CONDITIONS ON GROUP BY DATA ?
SELECT COUNTRY, STATE, CITY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY COUNTRY , STATE, CITY
HAVING sum(Population) > 15

-- QUERY 9: HOW TO APPLY CONDITIONS BEFORE AND AFTER GROUP BY ?
SELECT COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
WHERE  COUNTRY = 'COUNTRY1'			-- USED TO SPECIFY CONDITIONS ON NON-AGGREGATE VALUES
GROUP BY COUNTRY , STATE 
HAVING sum(Population) > 5			-- USED TO SPECIFY CONDITIONS ON AGGREGATE VALUES


-- QUERY 10: HOW TO REPORT TOTAL POPULATION USING ROLLUP  ?
SELECT  COUNTRY,  SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY COUNTRY

SELECT  COUNTRY,  SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)

SELECT  COUNTRY,  SUM(Population) AS TOTAL_POPULATION, GROUPING(COUNTRY) FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)


SELECT 
COUNTRY,
SUM(Population) AS TOTAL_POPULATION, GROUPING(COUNTRY) FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)
HAVING GROUPING(COUNTRY) = 0
UNION ALL
SELECT 
ISNULL(COUNTRY, 'GRAND TOTAL') AS COUNTRY,
SUM(Population) AS TOTAL_POPULATION, GROUPING(COUNTRY) FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)
HAVING GROUPING(COUNTRY) = 1


SELECT 
COUNTRY,
SUM(Population) AS TOTAL_POPULATION, GROUPING(COUNTRY) FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)
HAVING GROUPING(COUNTRY) = 0
UNION ALL
SELECT 
COALESCE(COUNTRY, 'GRAND TOTAL') AS COUNTRY,
SUM(Population) AS TOTAL_POPULATION, GROUPING(COUNTRY) FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)
HAVING GROUPING(COUNTRY) = 1

-- IS NULL						ISNULL



SELECT  COUNTRY, STATE,  SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(COUNTRY,STATE)			-- 11 ROWS
										-- COUNTRY WISE TOTAL + COUNTRY WISE STATE WISE TOTAL


SELECT  COUNTRY, STATE,  SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY CUBE(COUNTRY,STATE)			-- 13 ROWS
										-- COUNTRY WISE TOTAL + COUNTRY WISE STATE WISE TOTAL
										-- STATE WISE TOTAL





