-- DATE TIME CONVERSION STYLES (FOR BI REPORT DEVELOPERS):
SELECT GETDATE()									-- REPORTS DATE & TIME 
SELECT CONVERT(DATE, GETDATE())					-- REPORTS ONLY DATE 
SELECT CONVERT(TIME, GETDATE())					-- REPORTS ONLY TIME 
SELECT CONVERT(VARCHAR(30), GETDATE(), 101)			-- mm/dd/yyyy
SELECT CONVERT(VARCHAR(30), GETDATE(), 102)			-- yyyy.mm.dd
SELECT CONVERT(VARCHAR(30), GETDATE(), 103)			-- dd/mm/yyyy
SELECT CONVERT(VARCHAR(40), GETDATE(), 104)			-- dd.mm.yyyy
SELECT CONVERT(VARCHAR(30), GETDATE(), 105)			-- dd-mm-yyyy
SELECT CONVERT(VARCHAR(30), GETDATE(), 106)			-- dd MON YYYY
SELECT CONVERT(VARCHAR(30), GETDATE(), 107)			-- MON dd, YYYY

SELECT CONVERT(VARCHAR(30), GETDATE(), 108)			-- TIME 

SELECT CONVERT(VARCHAR(30), GETDATE(), 109)			-- DATE & TIME

SELECT YEAR(GETDATE())
SELECT MONTH(GETDATE())
SELECT DAY(GETDATE())

SELECT DATEDIFF(d, '2016-09-07', '2019-12-3') 			-- REPORTS DIFFERENCE IN DAYS
SELECT DATEDIFF(M, '2016-09-07 ', '2019-09-07') 		-- REPORTS DIFFERENCE IN MONTHS

SELECT DATEADD(d, 60, '2019-01-31')		-- ADDS n NUMBER OF DAYS TO EXISTING DATE
SELECT DATEADD(d, 1, GETDATE())			-- TO GET TOMORROW'S DATE
SELECT DATEADD(d, -1, GETDATE())		-- TO GET YESTERDAY'S DATE



-- STRING FUNCTIONS (FOR BI REPORT DEVELOPERS):
SELECT REPLACE('SQL SERVER', 'SQL','SEQUEL')	-- REPLACE TEXT IN A GIVEN STRING
SELECT REVERSE('SQL SERVER')					-- REVERSE THE TEXT
SELECT LEN('SQL SERVER')						-- REPORTS NUMBER OF CHARACTERS
SELECT UPPER('SQL Server')						-- REPORTS UPPER CASE TEXT
SELECT LOWER('SQL Server')						-- REPORTS LOWER CASE TEXT
SELECT SUBSTRING('SQL Server', 1, 3)		-- REPORTS CHARACTERS FROM STRING
SELECT LEFT('SQL Server', 3)				-- REPORTS CHARACTERS FROM LEFT OF THE STRING
SELECT RIGHT('SQL Server', 6)				-- REPORTS CHARACTERS FROM RIGHT OF THE STRING
SELECT ltrim ('  SQLserver')				-- TRUNCATE EXTRA SPACES BEFORE THE STRING VALUE
SELECT Rtrim ('SQLserver    ')				-- TRUNCATE EXTRA SPACES AFTER THE STRING VALUE

SELECT STUFF('ABCDE', 3, 2, ' ')

SELECT STUFF('SQLSERVER', 3 , 1,'L ')					
SELECT CHARINDEX(' ' , 'Indigo Montoya');  		-- REPORT POSITION OF CHARACTER
SELECT VALUE FROM STRING_SPLIT('SQL Server T-SQL Queries', ' ');


